sudo: required

services:
- docker

env:
  global:
  - DOCKER_USER=kittycashrobot
  # DOCKER_KEY=...
  - REGISTRY_USER=kittycashrobot
  # REGISTRY_PASS=...
  - secure: GfwuC8uTsYV4hweBuALExZ1g6XwdlzqgAj+5hRiq6xMvHHuSJsUh/SbbKS/5h4otu7FSpjdI2wYaiMa50/iV6e+663ACVtGCOmLS0ERVsVsDlfAPcIoiFGUzY0PilG38S918lFcGQabwDedW8A2hmdGkRgYsvgctUi2yXZerC7v2D+8qSBNYgHJxwqS6ciXWD/ISJ+VxL+lfCzoFzaEevwpCAcj96UpdBmUrf3qYTygY3Bfx9UV5AYV7lWc2LPmB+Qx/WT1i6NPimftieaw1rwNyTtY81KYwH6LuUNooIR73qxU2mfuLUcrWpUJak5oNDtjj1fY9IgZX2ehv/Otfg618YQ+NhTEr88caiZhV70XDTaTkBwvHxINVfsVY/JKwq5l++xNp2UMwsE55ab0k0LFbYInUpWgTT/7tQyqaJuFjzpyaEkwGj3thM+qo+TA2Cu4ZWbuukl4geqN6xBWduaRe/L3SZbOGYOiFbn5hDDF1OeGT8kKkeeq4XTQWg934GjvFF3FK3i1y8pOJK2TdaFoteHzDwHrUtmkB3wi8LynafIyMpdGuPewH1Ikc+coR9LugXlrYToUHG9IAH/aRrRBIgr2z9g31DiQG6klXDCOm+OTez6z5SmiY+Y2d5ROXsIec6eCdmr48iuBlIaIc9fV7Uw9I6x1ZsXJliY4/FE4=
  - secure: p+KWmpU4zbWgzCntN55GfZagdwg+7D9XLtdNRCKz+B6fC0Eu1RDYnkmqT10F3gtPiiNw7GaZYmoqR/7EkALN+QwSbvh4Gk+75m/0HyW+c2SogpE8l44O+PNjX6neAF1a9lsJm785hGCehHgHV8BBVBytUvFZpTEPlNSyYpG4kXYpsc2/n19TSAHLOvFbazSszJZujijZK2zjrAU3/eufTz4KmMBCnvt6y7DMAfPf2zQX9XpURYoBnyQd1d8dX/0XtX1DWBRiM4ApOiPIRPeLQHYtulLXT+y5cv6JQ+xDe+ANE93N7i9PIWrnbLT1pTuYQd/IF/1iLYUYGnP3NaMikIJy4s+8yMMStRJRcLkDBWecyYz7obxWoLc1Umy7ol+QGFRqHVuVbLGzje8n7/x5JKsHiSRCoAoHPQwuNmXtmdQOaP6KotTh1PNbkHfdcyO331viyDIVC2Lw+ngVE+C94TNI/JdKCVlSkQ+ZEGG3xsZ/Ik6NxJrCGfJiJFm/JxR8WQVhMoziTBGJZ7rejLMicyQBa5xZl0CJrO3dPp5bOunvWGKM9YC+gCSRYUbE9D/XdUY069J0XFFthMiGJZ/P0Tm7TFjWq5JlwZMVD5PnCjykDofWmHfZVZlXHEphaBl/neOZqtvsxNFVKeXLqxTonOLnP9EYNYpeDKBkHpiIfRs=

language: go

go:
- '1.9'
- '1.10'

before_script:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
- docker pull kittycash/teller || true

script:
- make test
- "./docker-build.sh"

after_script:
- docker images

deploy:
  provider: script
  script: "./docker-deploy.sh"
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^develop|master$ || $(git tag --points-at HEAD) != ""
